agent_options:
  path: ./lib/all/agent-options/agent-options.yml
org_settings:
  features:
    enable_host_users: true
    enable_software_inventory: true
  fleet_desktop:
    transparency_url: https://fleetdm.com/transparency
  host_expiry_settings:
    host_expiry_enabled: false
  integrations:
    google_calendar:
    - api_key_json: $DOGFOOD_CALENDAR_API_KEY
      domain: fleetdm.com
    jira: [ ]
    zendesk: [ ]
  mdm:
    end_user_authentication:
      entity_id: dogfood-eula.fleetdm.com
      idp_name: Google Workspace
      issuer_uri: $DOGFOOD_SSO_ISSUER_URI
      metadata: |-
        <?xml version="1.0" encoding="UTF-8" standalone="no"?>
        <md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://accounts.google.com/o/saml2?idpid=C01o3oocn" validUntil="2026-09-14T23:17:31.000Z">
        <md:IDPSSODescriptor WantAuthnRequestsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
        <md:KeyDescriptor use="signing">
        <ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
        <ds:X509Data>
        <ds:X509Certificate>MIIDdDCCAlygAwIBAgIGAXvrwEkDMA0GCSqGSIb3DQEBCwUAMHsxFDASBgNVBAoTC0dvb2dsZSBJ
        bmMuMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MQ8wDQYDVQQDEwZHb29nbGUxGDAWBgNVBAsTD0dv
        b2dsZSBGb3IgV29yazELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWEwHhcNMjEwOTE1
        MjMxNzMxWhcNMjYwOTE0MjMxNzMxWjB7MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEWMBQGA1UEBxMN
        TW91bnRhaW4gVmlldzEPMA0GA1UEAxMGR29vZ2xlMRgwFgYDVQQLEw9Hb29nbGUgRm9yIFdvcmsx
        CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A
        MIIBCgKCAQEA3MEEA4PqlMEZlz8UmmjNbbUehDQcf9TPUnURUxnUURw+KJOEuDv8E2xCsmjGpY9p
        vmGNIhIhVzohTpGjY9IQOychwbOsBHAzjgALJIo0UtUMu75dey4MG1vcQlWYpUFhzhZN+8b9hMkg
        fuLfzyl58r/w8W0iVqy7BwghWiFtM1wthtlzXEEFG9vCKaQt88iz2f1D//AX4MyxBPIRHB+IGBmb
        WTHrxAf/nnPUSnJaGmpKX5nC+rEMY+gxf5LfqREmohakvOU0QdKKyEFUcj3B/jIGQp5JTMuuH6fO
        WBh39iCFq6ruUj7ykUjnqzN8UA9IS4roxtczSh/bkwfBx3RYvQIDAQABMA0GCSqGSIb3DQEBCwUA
        A4IBAQC6Dkb6lYlCsdfapWjox2LJtp2PPaSyFvSaF0i2vJ2pTj3TLOijRUc5VKZYRuOgf228YeyQ
        GouvcuiKQvRA8tA/pv4bh4Rdbd/O7YrHZXCPQMOMUSL1SHc7v0F9AbxIg7BPYh19rFVznD5J4cbb
        ycrxQ1bwt1cGModQnLyCROoH23ZHAvyH/haaFLNOir7Uzc4vU/FGfie3QjEGqoBjnC6w/F/w0GAD
        Ho2h+JSJIlhydHolrIzc07lF0nfT+ShKA/l/waTD174JSkWW6rQ6MpCX5fGR7DLEYfRBby/Da5fA
        XkbUazMGv0D/m+FIvWmb60J+yuVHybMGRkFKWGOi4hTX</ds:X509Certificate>
        </ds:X509Data>
        </ds:KeyInfo>
        </md:KeyDescriptor>
        <md:NameIDFormat>urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress</md:NameIDFormat>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://accounts.google.com/o/saml2/idp?idpid=C01o3oocn"/>
        <md:SingleSignOnService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://accounts.google.com/o/saml2/idp?idpid=C01o3oocn"/>
        </md:IDPSSODescriptor>
        </md:EntityDescriptor>
      metadata_url: ""
    apple_business_manager:
    - organization_name: Fleet Device Management Inc.
      macos_team: "💻 Workstations" 
      ios_team: "📱🏢 Company-owned iPhones"
      ipados_team: "🔳🏢 Company-owned iPads"
    volume_purchasing_program:
    - location: Fleet Device Management Inc.
      teams:
      - "💻 Workstations"
      - "💻🐣 Workstations (canary)"
      - "📱🏢 Company-owned iPhones"
      - "🔳🏢 Company-owned iPads"
      - "📱🔐 Personally-owned iPhones"
  org_info:
    contact_url: https://fleetdm.com/company/contact
    org_logo_url: ""
    org_logo_url_light_background: ""
    org_name: Fleet
  secrets:
    - secret: $DOGFOOD_GLOBAL_ENROLL_SECRET
  server_settings:
    debug_host_ids:
      - 1
      - 3
    deferred_save_host: false
    enable_analytics: true
    live_query_disabled: false
    query_reports_disabled: false
    scripts_disabled: false
    server_url: https://dogfood.fleetdm.com
  sso_settings:
    enable_jit_provisioning: true
    enable_jit_role_sync: false
    enable_sso: true
    enable_sso_idp_login: false
    entity_id: dogfood.fleetdm.com
    idp_image_url: ""
    idp_name: Google Worksace
    issuer_uri: $DOGFOOD_SSO_ISSUER_URI
    metadata: |-
      $DOGFOOD_SSO_METADATA
    metadata_url: ""
  webhook_settings:
    failing_policies_webhook:
      destination_url: $DOGFOOD_FAILING_POLICIES_WEBHOOK_URL
      enable_failing_policies_webhook: true
      host_batch_size: 0
      policy_ids:
    host_status_webhook:
      days_count: 5
      destination_url: $DOGFOOD_HOST_STATUS_WEBHOOK_URL
      enable_host_status_webhook: true
      host_percentage: 20
    interval: 360m0s
    vulnerabilities_webhook:
      destination_url: $DOGFOOD_VULNERABILITIES_WEBHOOK_URL
      enable_vulnerabilities_webhook: true
      host_batch_size: 0
    activities_webhook:
      destination_url: $DOGFOOD_ACTIVITIES_WEBHOOK_URL
      enable_activities_webhook: true
policies:
  - path: ./lib/all/policies/mac-enrollment-profile-up-to-date.yml
queries:
  - path: ./lib/all/queries/collect-fleetd-information.yml
  - path: ./lib/all/queries/collect-operating-system-information.yml
  - path: ./lib/all/queries/collect-known-vulnerable-chrome-extensions.yml
controls: 
  enable_disk_encryption: true
  macos_migration:
    enable: true
    mode: voluntary
    webhook_url: $DOGFOOD_MACOS_MIGRATION_WEBHOOK_URL
  windows_enabled_and_configured: true
  windows_migration_enabled: true
